# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)


df = pd.read_csv("Housing.csv")


print("First 5 Rows:")
print(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Information:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())



X = df[['area', 'bedrooms', 'bathrooms']]
y = df['price']


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)



model = LinearRegression()

model.fit(X_train, y_train)


y_pred = model.predict(X_test)



mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

print("\n==============================")
print("MODEL PERFORMANCE")
print("==============================")

print("Mean Absolute Error :", mae)
print("Mean Squared Error  :", mse)
print("Root Mean Squared Error :", rmse)
print("R2 Score :", r2)



print("\n==============================")
print("MODEL COEFFICIENTS")
print("==============================")

print("Area Coefficient      :", model.coef_[0])
print("Bedrooms Coefficient  :", model.coef_[1])
print("Bathrooms Coefficient :", model.coef_[2])

print("Intercept :", model.intercept_)



results = pd.DataFrame({
    'Actual Price': y_test,
    'Predicted Price': y_pred
})

print("\nActual vs Predicted Prices")
print(results.head(10))



plt.figure(figsize=(8,6))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Price")

plt.ylabel("Predicted Price")

plt.title("Actual vs Predicted House Prices")

plt.show()



plt.figure(figsize=(6,4))

corr_matrix = df[['price','area','bedrooms','bathrooms']].corr()

sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Matrix")

plt.show()



plt.figure(figsize=(8,6))

plt.scatter(
    df['area'],
    df['price']
)

plt.xlabel("Area")

plt.ylabel("Price")

plt.title("Area vs Price")

plt.show()


sample_house = [[5000, 3, 2]]

predicted_price = model.predict(sample_house)

print("\n==============================")
print("SAMPLE PREDICTION")
print("==============================")

print("Area      : 5000 sq.ft")
print("Bedrooms  : 3")
print("Bathrooms : 2")

print("Predicted Price =", predicted_price[0])